### ISSUE TITLE
Does it have to be $$$?

### ISSUE THREAD

**Issue by fuermosi777** [adri567/CheesyChart#5]
Hello,

I recently came across this beautiful chart in the SwiftUI libraries and was impressed by its rarity. However, I noticed that it seems to be specifically designed for building price charts, as the value labels are always displayed with a "$" symbol and a currency format.

I was wondering if it would be possible to provide an option for users to modify the format of the value labels. This would make the library more accessible and appealing to a wider range of users globally.

Thank you for your time and consideration.

**Comment by adri567** [comment]
Hello fuermosi777,

I am appreciated for your feedback. With the newest update, it should work. You can choose between a currency chart and a normal chart. Just change "forCurrency" to false and "label" for your specific ending.

Best regards,
Adrian :)
